// <auto-generated />
namespace Inlämmningsuppgift_ASP.NET_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedproducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedproducts));
        
        string IMigrationMetadata.Id
        {
            get { return "201901170940319_added products"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
